# Generated by Django 4.0.3 on 2022-05-11 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id_client', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('observations', models.CharField(blank=True, max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id_drink', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('amount', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id_invoice', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant_app.client')),
            ],
        ),
        migrations.CreateModel(
            name='Saucer',
            fields=[
                ('id_saucer', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('amount', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id_table', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('num_diners', models.IntegerField(default=0)),
                ('ubications', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Waiter',
            fields=[
                ('id_waiter', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('last_name', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drinks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant_app.drink')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant_app.invoice')),
                ('saucers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant_app.saucer')),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant_app.table'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='waiter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant_app.waiter'),
        ),
    ]
